psql $DATABASE_URL -c "drop table new_practices; create table new_practices (original text, new text);"
psql $DATABASE_URL -c "\copy new_practices(original,new) from 'practices.csv' with(format csv, delimiter ',');"
psql $DATABASE_URL -c "update attributevalues av set value = new from new_practices np where av.value like '%' || np.original || '%' and av.aid = 2;"
psql $DATABASE_URL -c "insert into attributevalues(aid, value) select 2, 'AI/MLOps' from attributevalues where not exists(select 1 from attributevalues where aid =2 and value = 'AI/MLOps') ;"
psql $DATABASE_URL -c "create or replace view duplicates as  with a as (select count(*),value from attributevalues group by value,aid having count(*) >1), b as  (select av.value,av.aid, av.id, row_number() over(partition by av.value) as rowid from a join attributevalues av on av.value = a.value), c as (select b.value, b.id, b.aid,rowid from b) select c.value,c.id,c.aid,cc.id as newid, c.rowid from c left join (select * from c where rowid =1) cc on cc.value = c.value;"
psql $DATABASE_URL -c "update attributevalues set value = 'AI Assistants' where value = 'Generative AI & Assistants';"
psql $DATABASE_URL -c "update attributevalues set value = 'AI Assistants' where value = 'Generative AI + Assistants';"
psql $DATABASE_URL -c "update entityattributes e set vid = newid from duplicates d where e.vid = d.id and e.aid = d.aid;"
psql $DATABASE_URL -c "update relationship r set pavid = newid from duplicates d where r.pavid = d.id and r.paid = d.aid;"
psql $DATABASE_URL -c "update relationship r set cavid = newid from duplicates d where r.cavid = d.id and r.caid = d.aid;"
psql $DATABASE_URL -c "delete from attributevalues a where a.id in (select id from duplicates where rowid>1);"

